# Set sleep timeout to 35min (35*60*1000ms)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=2100000

# Enable mouse & smooth scrolling
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

# Optional: enable encoders
# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Shorten macro timers
CONFIG_ZMK_MACRO_DEFAULT_TAP_MS=5

# Enable experimental features (passkey, disabling 2m phy support)
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
